version: 2.0.{build}
skip_tags: true
image: Visual Studio 2017
environment:
  access_token:
    secure: Eq6BjtZ80BXKLwFMg76IjuQAvbLjbojIF/X/ARouGVhxPneJtgDfCXMPNgJ7KBKq
nuget:
  disable_publish_on_pr: true
build_script:
  - dotnet restore
  - dotnet pack --include-symbols --include-source -c Release /p:VersionPrefix=%APPVEYOR_BUILD_VERSION% Glob
test_script:
  - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput="..\coverage.xml" Glob.Tests\Glob.Tests.csproj
  - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
  - pip install codecov
  - codecov -f "coverage.xml"
artifacts:
  - path: 'Glob\**\*.nupkg'
on_success:
  - ps: |
      if (-not $env:APPVEYOR_PULL_REQUEST_NUMBER) {
          git config --global credential.helper store
          Add-Content "$HOME\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
          git config --global user.email "michael@ganss.org"
          git config --global user.name "Michael Ganss"
          git tag v$env:APPVEYOR_BUILD_VERSION
          git push origin --tags --porcelain
      }
