version: 1.0.{build}
install:
  - nuget restore
configuration: Release
platform: Any CPU
build:
  project: Glob.sln
  verbosity: minimal
environment:
  COVERALLS_REPO_TOKEN:
    secure: M1/ps4uvKyp3VsZg5MSDaec0va7qPOhZBRea7Yg7a89mbBXtZNmDNe7rMQV0Fl2Q
after_test:
# generate report for NUnit testing framework:
  - packages\OpenCover.4.5.3723\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:"packages\NUnit.Runners.2.6.4\tools\nunit-console.exe" -targetargs:"/noshadow /domain:single bin\release\Glob.dll" -output:coverage.xml
  - packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml
